---
- name: LAMP
  hosts: web
  tasks:
  - name: garantindo que o apache esta rodando
    dnf: name=httpd state=present

  - name: garantindo que o mysql esta rodando
    dnf: name=mysql state=present

  - name: garantindo que o php esta rodando
    dnf: name=php state=present
