---
- name: Configurando um script
  hosts: prod
  vars:
  tasks:
  - name: garantindo que o ssh esta rodando
    service: name=httpd state=started

  - name: garantindo que o ssh esta rodando
    service: name=mysql state=started

  - name: garantindo que o ssh esta rodando
    service: name=php state=started

