---
- name: Configurando um script
  hosts: prod
  tasks:
  - name: garantindo que o ssh esta rodando
    dnf: name=httpd state=present

  - name: garantindo que o ssh esta rodando
    dnf: name=mysql state=present

  - name: garantindo que o ssh esta rodando
    dnf: name=php state=present
